"""add quantity to sub_items

Revision ID: 3eecc118e35a
Revises: b9f00d4f3f23
Create Date: 2026-06-15 07:53:54.102728

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "3eecc118e35a"
down_revision = "b9f00d4f3f23"
branch_labels = None
depends_on = None


def upgrade():
    with op.batch_alter_table("sub_items", schema=None) as batch_op:
        batch_op.add_column(sa.Column("quantity", sa.Integer(), nullable=True))
    op.execute("UPDATE sub_items SET quantity = 1 WHERE quantity IS NULL")


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("sub_items", schema=None) as batch_op:
        batch_op.drop_column("quantity")

    # ### end Alembic commands ###
