"""add token_blocklist and auth_logs tables

Revision ID: a2043cab91c4
Revises: a1b2c3d4e5f6
Create Date: 2026-06-22 22:22:46.094724

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "a2043cab91c4"
down_revision = "a1b2c3d4e5f6"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "token_blocklist",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("jti", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("token_blocklist", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_token_blocklist_jti"), ["jti"], unique=True
        )

    op.create_table(
        "auth_logs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column("event", sa.String(length=32), nullable=False),
        sa.Column("ip", sa.String(length=45), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("auth_logs")
    with op.batch_alter_table("token_blocklist", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_token_blocklist_jti"))

    op.drop_table("token_blocklist")
    # ### end Alembic commands ###
